/*

 COURTYARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\Michael\Documents\Roms\GB\Homebrew Learning\tile_courtyard.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define courtyardWidth 40
#define courtyardHeight 18
#define courtyardBank 0

extern unsigned char courtyard[];

/* End of COURTYARD.H */
